// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjJclG_bCI0DiJ-JK-f71AnGJCNnDKegQ',
    appId: '1:878645575096:web:6bd2275723a6ee0c6ca34d',
    messagingSenderId: '878645575096',
    projectId: 'flutterfirebase-6e684',
    authDomain: 'flutterfirebase-6e684.firebaseapp.com',
    databaseURL: 'https://flutterfirebase-6e684-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterfirebase-6e684.appspot.com',
    measurementId: 'G-Z50EXDLBGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-SNH20MAAzoZlvaaFyA8hKel1aeYfeqU',
    appId: '1:878645575096:android:8639b0b1d0e596aa6ca34d',
    messagingSenderId: '878645575096',
    projectId: 'flutterfirebase-6e684',
    databaseURL: 'https://flutterfirebase-6e684-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterfirebase-6e684.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuLsKFk9ZP_rlzFKeaI45tczv3vVdZ_hI',
    appId: '1:878645575096:ios:9f26f48491e9d6cc6ca34d',
    messagingSenderId: '878645575096',
    projectId: 'flutterfirebase-6e684',
    databaseURL: 'https://flutterfirebase-6e684-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterfirebase-6e684.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuLsKFk9ZP_rlzFKeaI45tczv3vVdZ_hI',
    appId: '1:878645575096:ios:9f26f48491e9d6cc6ca34d',
    messagingSenderId: '878645575096',
    projectId: 'flutterfirebase-6e684',
    databaseURL: 'https://flutterfirebase-6e684-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterfirebase-6e684.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjJclG_bCI0DiJ-JK-f71AnGJCNnDKegQ',
    appId: '1:878645575096:web:c5029a2b5601a9c26ca34d',
    messagingSenderId: '878645575096',
    projectId: 'flutterfirebase-6e684',
    authDomain: 'flutterfirebase-6e684.firebaseapp.com',
    databaseURL: 'https://flutterfirebase-6e684-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterfirebase-6e684.appspot.com',
    measurementId: 'G-2DK3PBD6D1',
  );
}
